apiVersion: apps/v1
kind: Deployment
metadata:
  name: getuser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: getuser
  template:
    metadata:
      labels:
        app: getuser
    spec:
      containers:
        - name: getuser
          image: tbendr/getuser:2-linux
          ports:
            -  containerPort: 5000
