apiVersion: apps/v1
kind: Deployment
metadata:
  name: getuser
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: getuser
  template:
    metadata:
      labels:
        app: getuser
    spec:
      containers:
        - name: getuser
          image: tbendr/getuser:3-linux
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
