apiVersion: batch/v1
kind: CronJob
metadata:
  name: getuser-health-check
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-check
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - curl http://getuser-service/health && echo "Health check completed"
          restartPolicy: OnFailure 