apiVersion: apps/v1
kind: Deployment
metadata:
  name: getuser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: getuser
  template:
    metadata:
      labels:
        app: getuser
    spec:
      containers:
        - name: getuser
          image: tbendr/getuser:3-linux
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: getuser-config
                  key: APP_NAME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: getuser-config
                  key: PORT
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: getuser-config
                  key: MESSAGE
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: getuser-secret
                  key: SECRET_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
